include_directories(${CMAKE_SOURCE_DIR}/include)

add_executable(robotraconteurlite_tiny_service tiny_service/robotraconteurlite_tiny_service.c)
target_link_libraries(robotraconteurlite_tiny_service robotraconteurlite)

add_executable(robotraconteurlite_tiny_client tiny_client/robotraconteurlite_tiny_client.c)
target_link_libraries(robotraconteurlite_tiny_client robotraconteurlite)

add_executable(robotraconteurlite_tiny_service_no_funcptr tiny_no_funcptr/robotraconteurlite_tiny_service_no_funcptr.c)
target_link_libraries(robotraconteurlite_tiny_service_no_funcptr robotraconteurlite)

add_executable(robotraconteurlite_tiny_client_no_funcptr tiny_no_funcptr/robotraconteurlite_tiny_client_no_funcptr.c)
target_link_libraries(robotraconteurlite_tiny_client_no_funcptr robotraconteurlite)
