name: CI

on:
  push:
  pull_request:
  release:
    types:
    - created

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: robotraconteur ppa
      run: |
        sudo add-apt-repository ppa:robotraconteur/ppa -y
    - name: apt update
      run: |
        sudo apt-get update
    - name: apt
      run: |
        sudo apt-get install build-essential uuid-dev libssl-dev libcmocka-dev python3-robotraconteur -y
    - name: cmake
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        make
    - name: ctest
      run: |
        cd build
        ctest --output-on-failure
    - name: tiny tests
      run: |
        python3 test/tiny_test/tiny_client_ci_test.py
        python3 test/tiny_test/tiny_service_ci_test.py
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: apt update
      run: |
        sudo apt-get update
    - name: apt
      run: |
        sudo apt-get install build-essential uuid-dev libssl-dev libcmocka-dev -y
    - name: clang-tidy-14
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 14 all
    - name: cmake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -DCMAKE_C_CLANG_TIDY=clang-tidy-14 \
              -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: |
        cd build
        make -j2 -k

  cppcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: apt update
      run: |
        sudo apt-get update
    - name: apt
      run: |
        sudo apt-get install build-essential uuid-dev libssl-dev libcmocka-dev cppcheck  -y
    - name: cmake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -DCMAKE_C_FLAGS="-DCPPCHECK=1" \
        -DCMAKE_C_CPPCHECK="/usr/bin/cppcheck;--enable=warning;--inconclusive;--force;--inline-suppr;--error-exitcode=1;--std=c99;" \
        ..
    - name: make
      run: |
        cd build
        make -j2 -k

  pre-commit:
    runs-on: ubuntu-22.04
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y dos2unix
    - uses: pre-commit/action@v3.0.1
